services:

    LSB\LocaleBundle\Factory\CountryFactory: ~

    lsb_locale_factory_country:
        alias: LSB\LocaleBundle\Factory\CountryFactory
    LSB\LocaleBundle\Factory\CountryFactoryInterface: '@LSB\LocaleBundle\Factory\CountryFactory'

    LSB\LocaleBundle\Factory\CurrencyFactory: ~

    lsb_locale_factory_currency:
        alias: LSB\LocaleBundle\Factory\CurrencyFactory
    LSB\LocaleBundle\Factory\CurrencyFactoryInterface: '@LSB\LocaleBundle\Factory\CurrencyFactory'

    LSB\LocaleBundle\Factory\CurrencyExchangeRateFactory: ~

    lsb_locale_factory_currency_exchange_rate:
        alias: LSB\LocaleBundle\Factory\CurrencyExchangeRateFactory
    LSB\LocaleBundle\Factory\CurrencyExchangeRateFactoryInterface: '@LSB\LocaleBundle\Factory\CurrencyExchangeRateFactory'

    LSB\LocaleBundle\Factory\LanguageFactory: ~

    lsb_locale_factory_language:
        alias: LSB\LocaleBundle\Factory\LanguageFactory
    LSB\LocaleBundle\Factory\LanguageFactoryInterface: '@LSB\LocaleBundle\Factory\LanguageFactory'

    LSB\LocaleBundle\Factory\TaxFactory: ~

    lsb_locale_factory_tax:
        alias: LSB\LocaleBundle\Factory\TaxFactory
    LSB\LocaleBundle\Factory\TaxFactoryInterface: '@LSB\LocaleBundle\Factory\TaxFactory'